"use Strict";
const policy = require("./Controller");
const sessionAuth = require("../../services/sessionAuth");
const express = require("express");
const app = express.Router();

app.post("/addHRPolicy", sessionAuth, policy.addHRPolicy);
app.post("/viewHRPolicy", sessionAuth, policy.viewHRPolicy);
app.post("/deactivatepolicy", sessionAuth, policy.deactivatepolicy);
app.post("/addHREvent", sessionAuth, policy.addHREvent);
app.post("/viewHREvent", sessionAuth, policy.viewHREvent);
app.post("/eventmailnotify", sessionAuth, policy.eventmailnotify);
app.post("/addHoliday", sessionAuth, policy.addHoliday);
app.post("/viewHoliday", sessionAuth, policy.viewHoliday);
app.post("/deactivateEvent", sessionAuth, policy.deactivateEvent);
app.post("/uploadHoliday", sessionAuth, policy.uploadHoliday);
app.post("/hrreportview", sessionAuth, policy.hrreportview);
app.post("/hrreport", sessionAuth, policy.hrreport);
app.post("/croneoperation", sessionAuth, policy.croneoperation);
app.post("/getPolicyAgreement", sessionAuth, policy.getPolicyAgreement);
app.post("/agreePolicy", sessionAuth, policy.agreePolicy);
app.post("/getModulePolicy", sessionAuth, policy.getModulePolicy);
app.post("/OptionalHolidayConfig", sessionAuth, policy.OptionalHolidayConfig);
app.post("/hrAnalyticsDashboard", sessionAuth, policy.hrAnalyticsDashboardData);
app.post("/hiringTrend", sessionAuth, policy.hrAnalyticsHiringData);
app.post("/hrDashboard", sessionAuth, policy.hrDashboard);
app.post("/attritionRate", sessionAuth, policy.viewAttritionData);
app.post("/hiringAndLeftTrend", sessionAuth, policy.hiringAndLeftTrend);

module.exports = app;
